CREATE TABLE IF NOT EXISTS message_queue (
    id INT AUTO_INCREMENT NOT NULL,
    queue_id BIGINT NOT NULL,
    message VARCHAR(1024) NOT NULL,
    chat_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT NOT NULL,
    chat_id INT DEFAULT NULL,
    username VARCHAR(128) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS chat (
    id INT AUTO_INCREMENT NOT NULL,
    external_chat_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;


ALTER TABLE user ADD CONSTRAINT FK_8D93D6491A9A7125 FOREIGN KEY (chat_id) REFERENCES chat (id);
ALTER TABLE message_queue ADD CONSTRAINT FK_8D93D6491A9A7126 FOREIGN KEY (chat_id) REFERENCES chat (id);

CREATE UNIQUE INDEX UNIQ_8D93D6491A9A7125 ON user (chat_id);