// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: timezone_fetcher.proto

package timeZoneFetcherGRPCInterface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// date - `Y-m-d H:i:s` string (without timezone)
type RequestForTimeZone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *RequestForTimeZone) Reset() {
	*x = RequestForTimeZone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timezone_fetcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForTimeZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForTimeZone) ProtoMessage() {}

func (x *RequestForTimeZone) ProtoReflect() protoreflect.Message {
	mi := &file_timezone_fetcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForTimeZone.ProtoReflect.Descriptor instead.
func (*RequestForTimeZone) Descriptor() ([]byte, []int) {
	return file_timezone_fetcher_proto_rawDescGZIP(), []int{0}
}

func (x *RequestForTimeZone) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type TimeZoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timezone string `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
}

func (x *TimeZoneResponse) Reset() {
	*x = TimeZoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timezone_fetcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeZoneResponse) ProtoMessage() {}

func (x *TimeZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timezone_fetcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeZoneResponse.ProtoReflect.Descriptor instead.
func (*TimeZoneResponse) Descriptor() ([]byte, []int) {
	return file_timezone_fetcher_proto_rawDescGZIP(), []int{1}
}

func (x *TimeZoneResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

var File_timezone_fetcher_proto protoreflect.FileDescriptor

var file_timezone_fetcher_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x66, 0x65, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x22, 0x2e, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f,
	0x6e, 0x65, 0x32, 0x51, 0x0a, 0x16, 0x54, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x13, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65,
	0x1a, 0x11, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x46, 0x65, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x47, 0x52, 0x50, 0x43, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timezone_fetcher_proto_rawDescOnce sync.Once
	file_timezone_fetcher_proto_rawDescData = file_timezone_fetcher_proto_rawDesc
)

func file_timezone_fetcher_proto_rawDescGZIP() []byte {
	file_timezone_fetcher_proto_rawDescOnce.Do(func() {
		file_timezone_fetcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_timezone_fetcher_proto_rawDescData)
	})
	return file_timezone_fetcher_proto_rawDescData
}

var file_timezone_fetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_timezone_fetcher_proto_goTypes = []interface{}{
	(*RequestForTimeZone)(nil), // 0: RequestForTimeZone
	(*TimeZoneResponse)(nil),   // 1: TimeZoneResponse
}
var file_timezone_fetcher_proto_depIdxs = []int32{
	0, // 0: TimeZoneFetcherService.GetTimeZone:input_type -> RequestForTimeZone
	1, // 1: TimeZoneFetcherService.GetTimeZone:output_type -> TimeZoneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_timezone_fetcher_proto_init() }
func file_timezone_fetcher_proto_init() {
	if File_timezone_fetcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timezone_fetcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForTimeZone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timezone_fetcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeZoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timezone_fetcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timezone_fetcher_proto_goTypes,
		DependencyIndexes: file_timezone_fetcher_proto_depIdxs,
		MessageInfos:      file_timezone_fetcher_proto_msgTypes,
	}.Build()
	File_timezone_fetcher_proto = out.File
	file_timezone_fetcher_proto_rawDesc = nil
	file_timezone_fetcher_proto_goTypes = nil
	file_timezone_fetcher_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TimeZoneFetcherServiceClient is the client API for TimeZoneFetcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeZoneFetcherServiceClient interface {
	GetTimeZone(ctx context.Context, in *RequestForTimeZone, opts ...grpc.CallOption) (*TimeZoneResponse, error)
}

type timeZoneFetcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeZoneFetcherServiceClient(cc grpc.ClientConnInterface) TimeZoneFetcherServiceClient {
	return &timeZoneFetcherServiceClient{cc}
}

func (c *timeZoneFetcherServiceClient) GetTimeZone(ctx context.Context, in *RequestForTimeZone, opts ...grpc.CallOption) (*TimeZoneResponse, error) {
	out := new(TimeZoneResponse)
	err := c.cc.Invoke(ctx, "/TimeZoneFetcherService/GetTimeZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeZoneFetcherServiceServer is the server API for TimeZoneFetcherService service.
type TimeZoneFetcherServiceServer interface {
	GetTimeZone(context.Context, *RequestForTimeZone) (*TimeZoneResponse, error)
}

// UnimplementedTimeZoneFetcherServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTimeZoneFetcherServiceServer struct {
}

func (*UnimplementedTimeZoneFetcherServiceServer) GetTimeZone(context.Context, *RequestForTimeZone) (*TimeZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeZone not implemented")
}

func RegisterTimeZoneFetcherServiceServer(s *grpc.Server, srv TimeZoneFetcherServiceServer) {
	s.RegisterService(&_TimeZoneFetcherService_serviceDesc, srv)
}

func _TimeZoneFetcherService_GetTimeZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForTimeZone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeZoneFetcherServiceServer).GetTimeZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TimeZoneFetcherService/GetTimeZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeZoneFetcherServiceServer).GetTimeZone(ctx, req.(*RequestForTimeZone))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeZoneFetcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TimeZoneFetcherService",
	HandlerType: (*TimeZoneFetcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeZone",
			Handler:    _TimeZoneFetcherService_GetTimeZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timezone_fetcher.proto",
}
